// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jchbnjzcgswrogssalqx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpjaGJuanpjZ3N3cm9nc3NhbHF4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkwNTMxNjAsImV4cCI6MjA2NDYyOTE2MH0.8DalUZzyteLjMPYnM_uEjtvWbnIpapJSt2bfza9-6yM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);